name: schedule

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update weather
        run: bash weather.sh
	